# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # install angular
    - run: npm install -g @angular/cli
    - run: npm install --save-dev @angular-devkit/build-angular
    #build
    - run: ng build --prod --base-href /solocoding-blog/
    - run: npm run scully --scanRoutes --showGuessError
    - run: mkdir docs
    - run: cp -RT dist/static/ docs/
