# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependencies
      run: sudo npm install
    - name: Install cli
      run: sudo npm install -g @angular/cli
    - name: build app angular
      run: |
        ng build --prod --base-href /solocoding-blog/
        cp dist/soloCoding-blog/index.html dist/soloCoding-blog/404.html
    - name: build static scully
      run: npm run scully -- --scanRoutes --showGuessError
    - name: Commit work
      run: |
        cp -RT dist/static/ docs/
        git config --global user.name "s0l0c0ding"
        git config --global user.email "s0l0c0ding@users.noreply.github.com"
        git add .
        git commit -m"workflow"
        git push